# Generated by Django 4.2.25 on 2025-10-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0002_tweetmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweetmodel",
            name="text",
            field=models.TextField(max_length=2000),
        ),
    ]
