# Generated by Django 4.2.25 on 2025-11-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0003_alter_tweetmodel_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweetmodel", options={"ordering": ["-created_at"]},
        ),
    ]
