# Generated by Django 4.2.25 on 2025-11-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0004_alter_tweetmodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweetmodel",
            name="photo",
            field=models.ImageField(upload_to="photos/"),
        ),
    ]
