# Generated by Django 4.2.25 on 2025-11-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0005_alter_tweetmodel_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweetmodel",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="tweetmodel",
            name="text",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
