# Generated by Django 4.2.25 on 2025-12-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0006_alter_tweetmodel_photo_alter_tweetmodel_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tweet_count", models.IntegerField(default=0)),
                ("is_trending", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Hashtag",
                "verbose_name_plural": "Hashtags",
                "ordering": ["-tweet_count", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="tweet_hasht_slug_6a99b8_idx"),
                    models.Index(
                        fields=["-tweet_count"], name="tweet_hasht_tweet_c_e61460_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="tweetmodel",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="tweets", to="tweet.hashtag"
            ),
        ),
    ]
