# Generated by Django 4.2.25 on 2025-12-04 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0007_hashtag_tweetmodel_hashtags"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendingHashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recent_tweets", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hashtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trending_entries",
                        to="tweet.hashtag",
                    ),
                ),
            ],
            options={"ordering": ["-recent_tweets"],},
        ),
    ]
