# Generated by Django 4.2.25 on 2025-12-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0008_trendinghashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweetmodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retweets",
                to="tweet.tweetmodel",
            ),
        ),
    ]
