# Generated by Django 4.2.25 on 2025-10-14 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tweet", "0002_tweetmodel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReactionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reaction_type", models.CharField(max_length=6)),
                (
                    "tweet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tweet.tweetmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "tweet"], name="interaction_user_id_91b7ae_idx"
                    ),
                    models.Index(
                        fields=["tweet", "reaction_type"],
                        name="interaction_tweet_i_b64b59_idx",
                    ),
                ],
                "unique_together": {("user", "tweet", "reaction_type")},
            },
        ),
    ]
