# Generated by Django 4.2.25 on 2025-10-15 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweet", "0002_tweetmodel"),
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="reactionmodel", name="interaction_tweet_i_b64b59_idx",
        ),
        migrations.RenameField(
            model_name="reactionmodel",
            old_name="reaction_type",
            new_name="reactiontype",
        ),
        migrations.AlterUniqueTogether(
            name="reactionmodel", unique_together={("user", "tweet", "reactiontype")},
        ),
        migrations.AddIndex(
            model_name="reactionmodel",
            index=models.Index(
                fields=["tweet", "reactiontype"], name="interaction_tweet_i_bcb793_idx"
            ),
        ),
    ]
