# Generated by Django 4.2.25 on 2025-10-16 20:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0003_alter_tweetmodel_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interactions", "0003_comment"),
    ]

    operations = [
        migrations.RenameModel(old_name="Comment", new_name="CommentModel",),
        migrations.RemoveIndex(
            model_name="commentmodel", name="interaction_tweet_i_ff98d5_idx",
        ),
        migrations.RemoveIndex(
            model_name="commentmodel", name="interaction_user_id_c3f327_idx",
        ),
        migrations.RenameIndex(
            model_name="commentmodel",
            new_name="interaction_tweet_i_398652_idx",
            old_name="interaction_tweet_i_fc51ce_idx",
        ),
    ]
