# Generated by Django 4.2.25 on 2025-10-21 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interactions", "0004_rename_comment_commentmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reactiontype", models.CharField(max_length=6)),
            ],
        ),
        migrations.AddIndex(
            model_name="commentmodel",
            index=models.Index(
                fields=["tweet", "parent"], name="interaction_tweet_i_39a0cb_idx"
            ),
        ),
        migrations.AddField(
            model_name="commentlike",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_likes",
                to="interactions.commentmodel",
            ),
        ),
        migrations.AddField(
            model_name="commentlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="commentlike",
            index=models.Index(
                fields=["user", "reactiontype"], name="interaction_user_id_bf9ec1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentlike",
            index=models.Index(
                fields=["comment", "reactiontype"],
                name="interaction_comment_6f4dc2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentlike", unique_together={("user", "reactiontype")},
        ),
    ]
