# Generated by Django 4.2.25 on 2025-10-21 13:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interactions", "0005_commentlike_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commentlike", unique_together={("user", "comment", "reactiontype")},
        ),
    ]
