# Generated by Django 4.2.25 on 2025-10-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0006_alter_commentlike_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentmodel", old_name="likes_count", new_name="like_count",
        ),
    ]
