# Generated by Django 4.2.25 on 2025-10-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0007_rename_likes_count_commentmodel_like_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentmodel", options={"ordering": ["-created_at"]},
        ),
    ]
