# Generated by Django 4.2.25 on 2025-10-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0008_alter_commentmodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="reply_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="commentmodel",
            index=models.Index(
                fields=["parent"], name="interaction_parent__1d5dab_idx"
            ),
        ),
    ]
