# Generated by Django 4.2.25 on 2025-11-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
