# Generated by Django 4.2.25 on 2025-11-15 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0003_savedtweet"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "following_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-followed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "following_to"],
                        name="user_profil_user_id_646e3c_idx",
                    ),
                    models.Index(
                        fields=["following_to", "user"],
                        name="user_profil_followi_dcc2dd_idx",
                    ),
                ],
                "unique_together": {("user", "following_to")},
            },
        ),
    ]
