# Generated by Django 4.2.25 on 2025-11-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0004_followmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="follower_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="following_count",
            field=models.ImageField(default=0, upload_to=""),
        ),
    ]
