# Generated by Django 4.2.25 on 2025-11-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0005_userprofile_follower_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="following_count",
            field=models.IntegerField(default=0),
        ),
    ]
